# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5588044932c0ea0318480680a8decc316dbb4ea602491fdedd39bc88155413547bd123f2763186ef2b1872d50fe15b1766aa3c322a549ad44a4dcd970e60f8

test:
  secret_key_base: d2665aa8052ff35b13ce2d9e04a40459051bd7597859d79701e88ae3b1f5dea31313ffaa89747fd1f58fb3cb9f5a782f1cbfee91ef1ad5b22af1e24b8feb0a33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
